<a href="https://colab.research.google.com/github/kapikapiyo/my-firsrt-repo/blob/main/Ryoshi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
N = 10

In [5]:
w = np.random.rand(N)

In [6]:
w

array([0.42801216, 0.83897009, 0.48897574, 0.37416165, 0.35227284,
       0.12865694, 0.11163247, 0.15581154, 0.37553175, 0.86088449])

In [7]:
W = np.sum(w)

In [9]:
Q = np.zeros(N**2).reshape(N,N)

In [10]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
for i in range(N):
  for j in range(N):
    Q[i][j] = 4*w[i]*w[j]

In [12]:
Q

array([[0.73277763, 1.43635759, 0.83715025, 0.64058294, 0.60310824,
        0.22026693, 0.19112022, 0.26675693, 0.64292862, 1.47387612],
       [1.43635759, 2.81548322, 1.64094409, 1.25564173, 1.18218551,
        0.43175728, 0.37462522, 0.52288488, 1.26023962, 2.88902535],
       [0.83715025, 1.64094409, 0.95638911, 0.73182389, 0.6890115 ,
        0.25164048, 0.21834229, 0.30475225, 0.73450367, 1.68380654],
       [0.64058294, 1.25564173, 0.73182389, 0.55998777, 0.52722796,
        0.19255397, 0.16707436, 0.23319481, 0.56203832, 1.28843986],
       [0.60310824, 1.18218551, 0.6890115 , 0.52722796, 0.49638462,
        0.18128938, 0.15730035, 0.2195527 , 0.52915855, 1.21306491],
       [0.22026693, 0.43175728, 0.25164048, 0.19255397, 0.18128938,
        0.06621043, 0.05744917, 0.08018494, 0.19325906, 0.44303504],
       [0.19112022, 0.37462522, 0.21834229, 0.16707436, 0.15730035,
        0.05744917, 0.04984724, 0.06957451, 0.16768615, 0.38441066],
       [0.26675693, 0.52288488, 0.3047522

In [13]:
for i in range(N):
  Q[i][i] = Q[i][i] - 4*W*w[i]

In [14]:
Q

array([[ -6.31214785,   1.43635759,   0.83715025,   0.64058294,
          0.60310824,   0.22026693,   0.19112022,   0.26675693,
          0.64292862,   1.47387612],
       [  1.43635759, -10.99366128,   1.64094409,   1.25564173,
          1.18218551,   0.43175728,   0.37462522,   0.52288488,
          1.26023962,   2.88902535],
       [  0.83715025,   1.64094409,  -7.09197498,   0.73182389,
          0.6890115 ,   0.25164048,   0.21834229,   0.30475225,
          0.73450367,   1.68380654],
       [  0.64058294,   1.25564173,   0.73182389,  -5.59857785,
          0.52722796,   0.19255397,   0.16707436,   0.23319481,
          0.56203832,   1.28843986],
       [  0.60310824,   1.18218551,   0.6890115 ,   0.52722796,
         -5.30189909,   0.18128938,   0.15730035,   0.2195527 ,
          0.52915855,   1.21306491],
       [  0.22026693,   0.43175728,   0.25164048,   0.19255397,
          0.18128938,  -2.05143626,   0.05744917,   0.08018494,
          0.19325906,   0.44303504],
       [  

In [15]:
pip install openjij

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 50.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 4.0 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.27.1
    Uninstalling requests-2.27.1:
      Successfully uninstalled requests-2.27.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.27.1, but you have requests 2.28.2 which is incompatible.


In [16]:
from openjij import SQASampler

In [17]:
sampler = SQASampler()

In [18]:
sampleset = sampler.sample_qubo(Q, num_reads=10)

In [19]:
print(sampleset.record)

[([1, 1, 0, 0, 0, 1, 1, 0, 1, 0], -16.81046916, 1)
 ([1, 0, 0, 1, 0, 0, 0, 0, 1, 1], -16.93105813, 1)
 ([1, 0, 1, 0, 1, 0, 1, 1, 1, 0], -16.8481282 , 1)
 ([1, 1, 1, 0, 0, 1, 1, 0, 0, 0], -16.91749625, 1)
 ([0, 1, 1, 0, 1, 1, 1, 1, 0, 0], -16.93105813, 1)
 ([1, 0, 1, 1, 1, 0, 0, 0, 1, 0], -16.92655244, 1)
 ([1, 1, 0, 1, 0, 0, 1, 1, 1, 0], -16.72697389, 1)
 ([1, 0, 1, 1, 1, 0, 0, 1, 0, 1], -15.47966804, 1)
 ([1, 0, 0, 0, 1, 1, 0, 0, 0, 1], -16.60156125, 1)
 ([0, 0, 1, 1, 0, 0, 0, 0, 1, 1], -16.92539242, 1)]


In [22]:
x = sampleset.record[1][0]

In [23]:
x

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int8)

In [24]:
np.dot(w, x)

2.038590055448405

In [25]:
W -np.dot(w, x)

2.0763196220785707